import { formatToAyrsharePlatform } from "@/lib/social-platforms";

export interface PlatformPostTarget {
  id: string;
  label: string;
  composeUrl: string;
}

const PLATFORM_TARGETS: Record<string, PlatformPostTarget> = {
  twitter: {
    id: "twitter",
    label: "X (Twitter)",
    composeUrl: "https://twitter.com/compose/tweet",
  },
  linkedin: {
    id: "linkedin",
    label: "LinkedIn",
    composeUrl: "https://www.linkedin.com/feed/",
  },
  facebook: {
    id: "facebook",
    label: "Facebook",
    composeUrl: "https://www.facebook.com/",
  },
  instagram: {
    id: "instagram",
    label: "Instagram",
    composeUrl: "https://www.instagram.com/",
  },
  threads: {
    id: "threads",
    label: "Threads",
    composeUrl: "https://www.threads.net/",
  },
  tiktok: {
    id: "tiktok",
    label: "TikTok",
    composeUrl: "https://www.tiktok.com/",
  },
  youtube: {
    id: "youtube",
    label: "YouTube Studio",
    composeUrl: "https://studio.youtube.com/",
  },
  pinterest: {
    id: "pinterest",
    label: "Pinterest",
    composeUrl: "https://www.pinterest.com/pin-builder/",
  },
};

export function getPlatformTarget(format: string): PlatformPostTarget | null {
  const platform = formatToAyrsharePlatform(format);
  if (!platform) return null;
  return PLATFORM_TARGETS[platform] ?? null;
}

export function canOpenPlatform(format: string): boolean {
  return getPlatformTarget(format) !== null;
}

export async function copyToClipboard(text: string): Promise<void> {
  await navigator.clipboard.writeText(text);
}

export function downloadFile(
  filename: string,
  content: string,
  mimeType = "text/plain;charset=utf-8",
): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}

export function buildExportPack(
  title: string,
  outputs: Array<{ format: string; label: string; content: string }>,
): string {
  const header = `# ${title}\n\nGenerated by RepurAI — copy each section to the matching platform.\n\n---\n\n`;
  const sections = outputs
    .map(
      (o) =>
        `## ${o.label}\n\n${o.content.trim()}\n`,
    )
    .join("\n---\n\n");
  return header + sections;
}

function escapeIcs(value: string): string {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/;/g, "\\;")
    .replace(/,/g, "\\,")
    .replace(/\n/g, "\\n");
}

function toIcsUtc(date: Date): string {
  return `${date.toISOString().replace(/[-:]/g, "").split(".")[0]}Z`;
}

export interface IcsEventInput {
  uid: string;
  title: string;
  description: string;
  start: Date;
  durationMinutes?: number;
}

export function buildIcsCalendar(events: IcsEventInput[]): string {
  const lines = [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//RepurAI//Content Calendar//EN",
    "CALSCALE:GREGORIAN",
    "METHOD:PUBLISH",
  ];

  for (const event of events) {
    const end = new Date(event.start);
    end.setMinutes(end.getMinutes() + (event.durationMinutes ?? 15));

    lines.push(
      "BEGIN:VEVENT",
      `UID:${event.uid}`,
      `DTSTAMP:${toIcsUtc(new Date())}`,
      `DTSTART:${toIcsUtc(event.start)}`,
      `DTEND:${toIcsUtc(end)}`,
      `SUMMARY:${escapeIcs(event.title)}`,
      `DESCRIPTION:${escapeIcs(event.description)}`,
      "END:VEVENT",
    );
  }

  lines.push("END:VCALENDAR");
  return lines.join("\r\n");
}

export async function copyAndOpenPlatform(
  format: string,
  content: string,
): Promise<{ platform: PlatformPostTarget | null }> {
  const platform = getPlatformTarget(format);
  await copyToClipboard(content);
  if (platform) {
    window.open(platform.composeUrl, "_blank", "noopener,noreferrer");
  }
  return { platform };
}